name: Build and Deploy
on:
  push:
    branches: [master]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh  
            cd /var/www/personalmanagement
            git pull
            cd /var/www/personalmanagement/server
            npm install
            npm run build
            mkdir dist/logs
            cd /var/www/personalmanagement/client
            npm install
            npm run build
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.36.0
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          WITH_V: true
