name: Build and Deploy
on:
  push:
    branches: [master]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            cd /var/www/personalmanagement
            git pull
            cd /var/www/personalmanagement/server
            npm install
            npm run build
            cd /var/www/personalmanagement/client
            npm install
            npm run build
